JEIEvents.hideItems((event) => {
  event.hide('extendedcrafting:luminessence_block');
  event.hide('extendedcrafting:luminessence');
  event.hide('extendedcrafting:frame');
  event.hide('extendedcrafting:basic_table');
  event.hide('extendedcrafting:advanced_table');
  event.hide('extendedcrafting:ultimate_table');
  event.hide('extendedcrafting:basic_auto_table');
  event.hide('extendedcrafting:advanced_auto_table');
  event.hide('extendedcrafting:ultimate_auto_table');
  event.hide('extendedcrafting:ender_alternator');
  event.hide('extendedcrafting:black_iron_block');
  event.hide('extendedcrafting:redstone_ingot_block');
  event.hide('extendedcrafting:enhanced_redstone_ingot_block');
  event.hide('extendedcrafting:ender_ingot_block');
  event.hide('extendedcrafting:enhanced_ender_ingot_block');
  event.hide('extendedcrafting:crystaltine_block');
  event.hide('extendedcrafting:crafting_core');
  event.hide('extendedcrafting:elite_auto_table');
  event.hide('extendedcrafting:compressor');
  event.hide('extendedcrafting:auto_ender_crafter');
  event.hide('extendedcrafting:flux_alternator');
  event.hide('extendedcrafting:flux_crafter');
  event.hide('extendedcrafting:auto_flux_crafter');
  event.hide('extendedcrafting:black_iron_ingot');
  event.hide('extendedcrafting:black_iron_nugget');
  event.hide('extendedcrafting:black_iron_slate');
  event.hide('extendedcrafting:basic_catalyst');
  event.hide('extendedcrafting:advanced_catalyst');
  event.hide('extendedcrafting:elite_catalyst');
  event.hide('extendedcrafting:ultimate_catalyst');
  event.hide('extendedcrafting:redstone_catalyst');
  event.hide('extendedcrafting:enhanced_redstone_catalyst');
  event.hide('extendedcrafting:ender_catalyst');
  event.hide('extendedcrafting:enhanced_ender_catalyst');
  event.hide('extendedcrafting:crystaltine_catalyst');
  event.hide('extendedcrafting:crystaltine_nugget');
  event.hide('extendedcrafting:enhanced_ender_nugget');
  event.hide('extendedcrafting:enhanced_redstone_ingot');
  event.hide('extendedcrafting:ender_ingot');
  event.hide('extendedcrafting:enhanced_ender_ingot');
  event.hide('extendedcrafting:crystaltine_ingot');
  event.hide('extendedcrafting:enhanced_redstone_nugget');
  event.hide('extendedcrafting:ender_nugget');
  event.hide('extendedcrafting:crystaltine_nugget');
  event.hide('extendedcrafting:flux_star_block');
  event.hide('extendedcrafting:ender_crafter');
  event.hide('extendedcrafting:redstone_ingot');
  event.hide('extendedcrafting:ender_star_block');
  event.hide('extendedcrafting:pedestal');
  event.hide('extendedcrafting:the_ultimate_catalyst');
  event.hide('extendedcrafting:basic_component');
  event.hide('extendedcrafting:advanced_component');
  event.hide('extendedcrafting:elite_component');
  event.hide('extendedcrafting:ultimate_component');
  event.hide('extendedcrafting:redstone_component');
  event.hide('extendedcrafting:enhanced_redstone_component');
  event.hide('extendedcrafting:ender_component');
  event.hide('extendedcrafting:enhanced_ender_component');
  event.hide('extendedcrafting:crystaltine_component');
  event.hide('extendedcrafting:the_ultimate_component');
  event.hide('extendedcrafting:handheld_table');
  event.hide('cisco_mod:cisco_spawn_egg');
  event.hide('cisco_mod:dragon_seeker_missile_spawn_egg');
  event.hide('cisco_mod:after_image_spawn_egg');
  event.hide('cisco_mod:fellkingboss_spawn_egg');
  event.hide('cisco_mod:legionnaire_kingsguard_spawn_egg');
  event.hide('cisco_mod:legionnaire_jotunn_spawn_egg');
  event.hide(Item.of('extendedcrafting:singularity', '{Id:"extendedcrafting:lapis_lazuli"}'));
  event.hide(Item.of('extendedcrafting:singularity', '{Id:"extendedcrafting:iron"}'));
  event.hide(Item.of('extendedcrafting:singularity', '{Id:"extendedcrafting:emerald"}'));
  event.hide(Item.of('extendedcrafting:singularity', '{Id:"extendedcrafting:gold"}'));
  event.hide(Item.of('extendedcrafting:singularity', '{Id:"extendedcrafting:glowstone"}'));
  event.hide(Item.of('extendedcrafting:singularity', '{Id:"extendedcrafting:redstone"}'));
  event.hide('extendedcrafting:redstone_nugget');  // Adicione quantos itens precisar
});